name: Cron

on:
  schedule:
  # Run every Monday at 08:30.
  - cron: "30 8 * * 1"

jobs:
  versions:
    uses: ./.github/workflows/versions.yml

  build_sdist:
    needs: versions
    uses: ./.github/workflows/build-sdist.yml
    with:
      glpk_version: ${{ needs.versions.outputs.glpk_version }}

  build_wheels:
    needs: versions
    uses: ./.github/workflows/build-wheels.yml
    with:
      glpk_version: ${{ needs.versions.outputs.glpk_version }}
